# Site settings
title: "Archit Pandey"
description: "Life, one byte at a time."
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "Archit Pandey"

# Build settings
kramdown:
  input: GFM
permalink: pretty
